server:
  port: 8080
spring:
  application:
    name: nps7
  jackson:
    serialization:
      fail-on-empty-beans: false
  datasource:
    url: jdbc:mysql://localhost:3306/bdcantina?useSSL=false&allowPublicKeyRetrieval=true&useTimezone=true&serverTimezone=GMT
    username: root
    password: root
    initialization-mode: always
  jpa:
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        show-sql: false
        format_sql: true
        enable_lazy_load_no_trans: true
    hibernate.ddl-auto: update
logging:
  pattern: console=%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n
  level:
    br:
      com:
        sevencomm: trace
    org:
      hibernate:
        SQL: false